service: formless

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  environment:
    ALLOW_ALL_DOMAINS: ""
    ALLOWED_DOMAINS: ""
    MAILGUN_API_KEY: ""
    MAILGUN_FROM_EMAIL: ""
    MAILGUN_DOMAIN: ""
    SMTP_SERVER: "" 
    SMTP_EMAIL: ""
    SMTP_PASSWORD: ""
    SMTP_PORT: ""

functions:
  handleForm:
    handler: handler.handleForm
    events:
      - http:
          path: handle-form
          method: post
          cors: true